name: ManHunt
version: @version@
main: io.ib67.manhunt.ManHunt
api-version: 1.16
commands:
  vote:
    description: vote
    usage: /vote
    default: all
  hunt:
    description: edit the runner.
    usage: /hunt <player_name>
    default: op